import {
  User,
  UserRole,
  Project,
  WorkOrder,
  MeasurementRecord,
  Invoice,
  Payment,
  InspectionRecord,
  MaterialCertificate,
  SiteEvidence,
  AIAlert,
  AuditCase,
  InquiryDirective,
  FundHold,
  AuditLog,
  SystemConfig,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-contractor-01',
    fullName: 'Rajesh Patil',
    email: 'contractor@mplads.gov.in',
    mobile: '9822011234',
    role: UserRole.CONTRACTOR,
    designation: 'Managing Director',
    organization: 'Patil Infrastructure & Works Pvt Ltd',
    district: 'Nashik',
    state: 'Maharashtra',
    isActive: true,
    createdAt: '2025-01-10T10:00:00Z',
    lastLogin: '2026-09-11T16:30:00Z',
    password: 'Demo@1234',
    twoFactorEnabled: false,
    isEmailVerified: true,
    isMobileVerified: true,
    emailVerifiedAt: '2026-08-15T10:00:00Z',
    mobileVerifiedAt: '2026-08-15T10:05:00Z',
  },
  {
    id: 'usr-engineer-01',
    fullName: 'Er. Vikram Shinde',
    email: 'pwd.engineer@mplads.gov.in',
    mobile: '9822055678',
    role: UserRole.PWD_ENGINEER,
    designation: 'Executive Engineer (Civil)',
    department: 'Public Works Department, Division 2',
    district: 'Nashik',
    state: 'Maharashtra',
    isActive: true,
    createdAt: '2024-11-15T09:00:00Z',
    lastLogin: '2026-09-11T18:45:00Z',
    password: 'Demo@1234',
    twoFactorEnabled: false,
    isEmailVerified: true,
    isMobileVerified: true,
    emailVerifiedAt: '2026-08-15T10:00:00Z',
    mobileVerifiedAt: '2026-08-15T10:05:00Z',
  },
  {
    id: 'usr-collector-01',
    fullName: 'Smt. Sunita Rao, IAS',
    email: 'collector.nashik@mplads.gov.in',
    mobile: '9422099887',
    role: UserRole.COLLECTOR,
    designation: 'District Collector & District Magistrate',
    department: 'District Administration',
    district: 'Nashik',
    state: 'Maharashtra',
    isActive: true,
    createdAt: '2024-06-01T08:00:00Z',
    lastLogin: '2026-09-11T17:15:00Z',
    password: 'Demo@1234',
    twoFactorEnabled: false,
    isEmailVerified: true,
    isMobileVerified: true,
    emailVerifiedAt: '2026-08-15T10:00:00Z',
    mobileVerifiedAt: '2026-08-15T10:05:00Z',
  },
  {
    id: 'usr-auditor-01',
    fullName: 'Arunabh Sengupta',
    email: 'cag.auditor@cag.gov.in',
    mobile: '9811022334',
    role: UserRole.CAG_AUDITOR,
    designation: 'Principal Director of Audit',
    department: 'Comptroller & Auditor General of India',
    state: 'Maharashtra',
    isActive: true,
    createdAt: '2024-05-10T11:00:00Z',
    lastLogin: '2026-09-11T19:00:00Z',
    password: 'Demo@1234',
    twoFactorEnabled: false,
    isEmailVerified: true,
    isMobileVerified: true,
    emailVerifiedAt: '2026-08-15T10:00:00Z',
    mobileVerifiedAt: '2026-08-15T10:05:00Z',
  },
  {
    id: 'usr-admin-01',
    fullName: 'Dr. K. Radhakrishnan',
    email: 'admin.mplads@nic.in',
    mobile: '9868012345',
    role: UserRole.ADMIN,
    designation: 'Joint Secretary (MPLADS Monitoring)',
    department: 'Ministry of Statistics & Programme Implementation',
    state: 'National',
    isActive: true,
    createdAt: '2024-01-01T09:00:00Z',
    lastLogin: '2026-09-11T19:20:00Z',
    password: 'Demo@1234',
    twoFactorEnabled: false,
    isEmailVerified: true,
    isMobileVerified: true,
    emailVerifiedAt: '2026-08-15T10:00:00Z',
    mobileVerifiedAt: '2026-08-15T10:05:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-p101',
    code: 'P101',
    name: 'Upgradation of Primary Health Center',
    description: 'Renovation of OPD wards, emergency triage rooms, and solar water heating at Baramati PHC.',
    category: 'Healthcare & Sanitation',
    district: 'Pune',
    state: 'Maharashtra',
    constituency: 'Baramati (Lok Sabha)',
    mpName: 'Hon. Smt. Supriya Sule',
    sanctionDate: '2025-03-15',
    sanctionAmount: 2000000,
    contractAmount: 1940000,
    expenditure: 700000,
    balanceAmount: 1300000,
    financialProgressPercent: 35,
    physicalProgressPercent: 40,
    startDate: '2025-04-01',
    expectedCompletionDate: '2026-10-31',
    delayDays: 0,
    status: 'IN_PROGRESS',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    executiveEngineer: 'Er. Vikram Shinde',
    riskScore: 22,
    riskLevel: 'LOW',
    riskReasons: ['Minor timeline slip of 5 days', 'Measurements consistent with invoice claims'],
    disproveChecklist: ['Regular site photo updates', 'Periodic E-MB counter-signatures'],
    coordinates: { lat: 18.1517, lng: 74.5772 },
    locationAddress: 'PHC Campus, Sector 3, Baramati, Dist Pune',
    technicalSanctionNo: 'TS/PWD/PUN/2025/089',
    administrativeSanctionNo: 'AS/MPLADS/PUN/2025/112',
    lastInspectionDate: '2026-08-20',
  },
  {
    id: 'proj-p102',
    code: 'P102',
    name: 'Rural Community Hall & Multipurpose Shed',
    description: 'Construction of 400-capacity community hall with reinforced concrete column frame and zinc sheet roofing at Niphad.',
    category: 'Community Infrastructure',
    district: 'Nashik',
    state: 'Maharashtra',
    constituency: 'Dindori (Lok Sabha)',
    mpName: 'Hon. Dr. Bharati Pawar',
    sanctionDate: '2024-08-10',
    sanctionAmount: 2500000,
    contractAmount: 2480000,
    expenditure: 2300000,
    balanceAmount: 200000,
    financialProgressPercent: 92,
    physicalProgressPercent: 45,
    startDate: '2024-09-01',
    expectedCompletionDate: '2025-05-31',
    delayDays: 285,
    status: 'DELAYED',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    executiveEngineer: 'Er. Vikram Shinde',
    riskScore: 86,
    riskLevel: 'CRITICAL',
    riskReasons: [
      'Significant financial vs physical progress deviation: 92% funds disbursed against 45% verified physical completion',
      'Overdue project: Delayed by 285 days beyond contractual completion deadline',
      'Text and geospatial similarity match of 91% with overlapping project P108 in adjacent ward',
      'Disproportionate invoice velocity in final quarter before physical milestone completion',
    ],
    disproveChecklist: [
      'Fresh physical inspection report with geo-tagged 360-degree photos showing roof completion',
      'Approved revised E-MB book verified by Executive Engineer explaining measurement delta',
      'Documented justification for unspent material lying on-site',
      'Reconciliation of duplicate bill reference INV-2025-099',
    ],
    coordinates: { lat: 20.0768, lng: 74.1084 },
    locationAddress: 'Gat No. 142, Niphad Taluka, Nashik District',
    technicalSanctionNo: 'TS/PWD/NSK/2024/401',
    administrativeSanctionNo: 'AS/MPLADS/NSK/2024/044',
    lastInspectionDate: '2026-07-15',
  },
  {
    id: 'proj-p103',
    code: 'P103',
    name: 'Installation of High-Mast Solar Lighting',
    description: 'Deployment of 12 energy-efficient LED high-mast towers with automatic day/night sensors in Hingna rural junctions.',
    category: 'Renewable Energy & Lighting',
    district: 'Nagpur',
    state: 'Maharashtra',
    constituency: 'Nagpur (Lok Sabha)',
    mpName: 'Hon. Shri Nitin Gadkari',
    sanctionDate: '2025-01-20',
    sanctionAmount: 1500000,
    contractAmount: 1475000,
    expenditure: 1275000,
    balanceAmount: 225000,
    financialProgressPercent: 85,
    physicalProgressPercent: 90,
    startDate: '2025-02-15',
    expectedCompletionDate: '2026-09-30',
    delayDays: 0,
    status: 'IN_PROGRESS',
    contractorId: 'usr-contractor-02',
    contractorName: 'Surya Vidyut Green Systems',
    executiveEngineer: 'Er. Sandeep Bapat',
    riskScore: 14,
    riskLevel: 'LOW',
    riskReasons: ['Progress aligned with milestones', 'Quality lab test certificates approved'],
    disproveChecklist: ['Final electrical inspector safety clearance'],
    coordinates: { lat: 21.0667, lng: 78.9667 },
    locationAddress: 'Hingna Industrial & Gramin Junctions, Nagpur',
    technicalSanctionNo: 'TS/PWD/NGP/2025/119',
    administrativeSanctionNo: 'AS/MPLADS/NGP/2025/205',
    lastInspectionDate: '2026-09-02',
  },
  {
    id: 'proj-p104',
    code: 'P104',
    name: 'Public Library & Digital Learning Center',
    description: 'Construction of 2-storey library with 50 computer cubicles, fiber connectivity, and reading halls in Chembur.',
    category: 'Education & Youth',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    constituency: 'Mumbai South Central (Lok Sabha)',
    mpName: 'Hon. Shri Rahul Shewale',
    sanctionDate: '2024-11-05',
    sanctionAmount: 3000000,
    contractAmount: 2950000,
    expenditure: 2340000,
    balanceAmount: 660000,
    financialProgressPercent: 78,
    physicalProgressPercent: 50,
    startDate: '2024-12-01',
    expectedCompletionDate: '2026-03-31',
    delayDays: 164,
    status: 'DELAYED',
    contractorId: 'usr-contractor-03',
    contractorName: 'Metro Buildcon Infra LLP',
    executiveEngineer: 'Er. Vikrant Deshmukh',
    riskScore: 74,
    riskLevel: 'HIGH',
    riskReasons: [
      'Significant financial vs physical gap (78% paid vs 50% physical work)',
      'Item rate deviations 32% above Maharashtra PWD District Schedule of Rates (DSR)',
      'Delayed by 164 days with no approved extension of time order',
    ],
    disproveChecklist: [
      'DSR deviation justification document approved by Superintending Engineer',
      'Verified computer hardware delivery receipts and serial number audit',
    ],
    coordinates: { lat: 19.0522, lng: 72.8995 },
    locationAddress: 'Plot 88, Ghatkopar-Mahul Link Road, Chembur East, Mumbai',
    technicalSanctionNo: 'TS/PWD/MUM/2024/778',
    administrativeSanctionNo: 'AS/MPLADS/MUM/2024/310',
    lastInspectionDate: '2026-06-25',
  },
  {
    id: 'proj-p105',
    code: 'P105',
    name: 'Construction of Concrete Approach Road',
    description: '1.8 km CC road with side storm drains connecting Wategaon village to State Highway 144.',
    category: 'Roads & Bridges',
    district: 'Satara',
    state: 'Maharashtra',
    constituency: 'Satara (Lok Sabha)',
    mpName: 'Hon. Shri Chhatrapati Udayanraje',
    sanctionDate: '2025-02-01',
    sanctionAmount: 1800000,
    contractAmount: 1760000,
    expenditure: 1116000,
    balanceAmount: 684000,
    financialProgressPercent: 62,
    physicalProgressPercent: 55,
    startDate: '2025-02-20',
    expectedCompletionDate: '2026-11-15',
    delayDays: 20,
    status: 'IN_PROGRESS',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    executiveEngineer: 'Er. Vikram Shinde',
    riskScore: 48,
    riskLevel: 'MEDIUM',
    riskReasons: [
      'Moderate physical vs financial gap (7% variance)',
      'Core sample compressive strength report pending for 200m stretch',
    ],
    disproveChecklist: [
      'Submission of NABL-accredited 28-day concrete cube compressive test certificate',
    ],
    coordinates: { lat: 17.6805, lng: 74.0183 },
    locationAddress: 'Wategaon Village Road, Karad Taluka, Satara',
    technicalSanctionNo: 'TS/PWD/SAT/2025/312',
    administrativeSanctionNo: 'AS/MPLADS/SAT/2025/119',
    lastInspectionDate: '2026-08-11',
  },
  {
    id: 'proj-p106',
    code: 'P106',
    name: 'Renovation of Water Filtration Plant',
    description: 'Replacing sand filter beds, dual-membrane RO systems, and overhead booster storage at Paithan.',
    category: 'Drinking Water Supply',
    district: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    constituency: 'Aurangabad (Lok Sabha)',
    mpName: 'Hon. Shri Sandipan Bhumre',
    sanctionDate: '2024-10-12',
    sanctionAmount: 4000000,
    contractAmount: 3910000,
    expenditure: 2600000,
    balanceAmount: 1400000,
    financialProgressPercent: 65,
    physicalProgressPercent: 30,
    startDate: '2024-11-01',
    expectedCompletionDate: '2025-09-30',
    delayDays: 346,
    status: 'DELAYED',
    contractorId: 'usr-contractor-04',
    contractorName: 'Jal-Shakti Environmental Engineers',
    executiveEngineer: 'Er. Aniket Joshi',
    riskScore: 79,
    riskLevel: 'HIGH',
    riskReasons: [
      'Severe physical delay: 35% financial disbursements in excess of verified physical delivery',
      'Unmatched vendor invoice reference with duplicate sub-contractor tax ID',
      'Field inspection note raised query on thickness of filtration media',
    ],
    disproveChecklist: [
      'Joint inspection report signed by District Water Quality Officer and EE',
      'Reconciliation of equipment manufacturer warranty certificates',
    ],
    coordinates: { lat: 19.4795, lng: 75.3831 },
    locationAddress: 'Paithan Municipal Filtration Works, Paithan',
    technicalSanctionNo: 'TS/PWD/AUR/2024/902',
    administrativeSanctionNo: 'AS/MPLADS/AUR/2024/552',
    lastInspectionDate: '2026-05-18',
  },
  {
    id: 'proj-p107',
    code: 'P107',
    name: 'Community Sanitation & Hygiene Complex',
    description: 'Prefabricated eco-sanitation facility with solar lights, sanitary napkin incinerator, and greywater recycling.',
    category: 'Healthcare & Sanitation',
    district: 'Thane',
    state: 'Maharashtra',
    constituency: 'Kalyan (Lok Sabha)',
    mpName: 'Hon. Dr. Shrikant Shinde',
    sanctionDate: '2024-04-10',
    sanctionAmount: 1200000,
    contractAmount: 1180000,
    expenditure: 1180000,
    balanceAmount: 20000,
    financialProgressPercent: 100,
    physicalProgressPercent: 100,
    startDate: '2024-05-01',
    expectedCompletionDate: '2024-12-31',
    actualCompletionDate: '2024-12-20',
    delayDays: 0,
    status: 'COMPLETED',
    contractorId: 'usr-contractor-05',
    contractorName: 'Swachh Bharat CleanTech Solutions',
    executiveEngineer: 'Er. Nilesh Kamat',
    riskScore: 10,
    riskLevel: 'LOW',
    riskReasons: ['Fully completed on schedule', 'Completion certificate issued by Gram Panchayat'],
    disproveChecklist: ['Handover documentation verified'],
    coordinates: { lat: 19.2183, lng: 72.9781 },
    locationAddress: 'Ward 12, Ambernath Road, Thane',
    technicalSanctionNo: 'TS/PWD/THN/2024/110',
    administrativeSanctionNo: 'AS/MPLADS/THN/2024/088',
    lastInspectionDate: '2025-01-10',
  },
  {
    id: 'proj-p108',
    code: 'P108',
    name: 'Construction of Multipurpose Hall, Ward 4',
    description: 'Erection of community hall shed with concrete base and event staging in Ward 4, Niphad.',
    category: 'Community Infrastructure',
    district: 'Nashik',
    state: 'Maharashtra',
    constituency: 'Dindori (Lok Sabha)',
    mpName: 'Hon. Dr. Bharati Pawar',
    sanctionDate: '2025-04-18',
    sanctionAmount: 2400000,
    contractAmount: 2350000,
    expenditure: 600000,
    balanceAmount: 1800000,
    financialProgressPercent: 25,
    physicalProgressPercent: 20,
    startDate: '2025-05-10',
    expectedCompletionDate: '2026-12-31',
    delayDays: 0,
    status: 'ON_HOLD',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    executiveEngineer: 'Er. Vikram Shinde',
    riskScore: 82,
    riskLevel: 'CRITICAL',
    riskReasons: [
      'Potential duplicate / overlapping work with Project P102 (Similarity: 91%)',
      'Geographic proximity within 650 meters of another community hall sanction in the same village',
      'Same contractor and nearly identical work specifications',
    ],
    disproveChecklist: [
      'Gram Sabha resolution explicitly demonstrating distinct beneficiary group and separate survey number',
      'Site GIS boundary demarcation map verified by Talathi/Tahsildar',
    ],
    coordinates: { lat: 20.0792, lng: 74.1132 },
    locationAddress: 'Ward 4, Near Maruti Temple, Niphad Taluka, Nashik',
    technicalSanctionNo: 'TS/PWD/NSK/2025/180',
    administrativeSanctionNo: 'AS/MPLADS/NSK/2025/091',
    lastInspectionDate: '2026-07-22',
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-101',
    projectId: 'proj-p101',
    projectCode: 'P101',
    projectName: 'Upgradation of Primary Health Center',
    workOrderNumber: 'WO/PWD/2025/P101/01',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    awardedAmount: 1940000,
    issueDate: '2025-03-25',
    stipulatedCompletionDate: '2026-10-31',
    scopeOfWork: 'Civil remodeling of OPD wards, tile flooring, sanitary fixtures, and 5kVA rooftop solar system installation.',
    status: 'ACTIVE',
  },
  {
    id: 'wo-102',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    workOrderNumber: 'WO/PWD/2024/P102/09',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    awardedAmount: 2480000,
    issueDate: '2024-08-20',
    stipulatedCompletionDate: '2025-05-31',
    scopeOfWork: 'Civil excavation, RCC column foundation, pre-engineered structural steel truss, and corrugated color-coated roofing.',
    status: 'ACTIVE',
  },
  {
    id: 'wo-103',
    projectId: 'proj-p103',
    projectCode: 'P103',
    projectName: 'Installation of High-Mast Solar Lighting',
    workOrderNumber: 'WO/PWD/2025/P103/04',
    contractorId: 'usr-contractor-02',
    contractorName: 'Surya Vidyut Green Systems',
    awardedAmount: 1475000,
    issueDate: '2025-02-01',
    stipulatedCompletionDate: '2026-09-30',
    scopeOfWork: 'Supply and erection of 12 numbers 12.5m octagonal poles, 4x100W LED luminaires, and monocrystalline solar array.',
    status: 'ACTIVE',
  },
  {
    id: 'wo-104',
    projectId: 'proj-p104',
    projectCode: 'P104',
    projectName: 'Public Library & Digital Learning Center',
    workOrderNumber: 'WO/PWD/2024/P104/11',
    contractorId: 'usr-contractor-03',
    contractorName: 'Metro Buildcon Infra LLP',
    awardedAmount: 2950000,
    issueDate: '2024-11-20',
    stipulatedCompletionDate: '2026-03-31',
    scopeOfWork: 'Two floor civil construction, acoustic ceiling, electrical cabling for 50 LAN terminals, and HVAC split units.',
    status: 'ACTIVE',
  },
  {
    id: 'wo-105',
    projectId: 'proj-p105',
    projectCode: 'P105',
    projectName: 'Construction of Concrete Approach Road',
    workOrderNumber: 'WO/PWD/2025/P105/03',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    awardedAmount: 1760000,
    issueDate: '2025-02-10',
    stipulatedCompletionDate: '2026-11-15',
    scopeOfWork: '1.8 km M25 grade cement concrete road paving with WMM base and precast drain culverts.',
    status: 'ACTIVE',
  },
];

export const INITIAL_MEASUREMENTS: MeasurementRecord[] = [
  {
    id: 'emb-001',
    projectId: 'proj-p101',
    projectCode: 'P101',
    projectName: 'Upgradation of Primary Health Center',
    embNumber: 'EMB-PWD-2025-044',
    pageNumber: 14,
    itemDescription: 'Vitrified ceramic tile flooring 600x600mm laid on 20mm cement mortar 1:4',
    claimedQuantity: 450,
    measuredQuantity: 442,
    unit: 'Sq.Mtr',
    ratePerUnit: 820,
    totalClaimedAmount: 369000,
    totalVerifiedAmount: 362440,
    submissionDate: '2026-07-10',
    submittedBy: 'Patil Infrastructure & Works Pvt Ltd',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Er. Vikram Shinde',
    verificationDate: '2026-07-15',
    engineerRemarks: 'Measurements cross-verified with physical tape measurements on site. Deduction of 8 sq.m for untreated elevator shaft area.',
  },
  {
    id: 'emb-002',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    embNumber: 'EMB-PWD-2024-118',
    pageNumber: 52,
    itemDescription: 'Supply and fixing of structural steel tubular truss framework with anti-corrosive primer coating',
    claimedQuantity: 18500,
    measuredQuantity: 9200,
    unit: 'Kg',
    ratePerUnit: 95,
    totalClaimedAmount: 1757500,
    totalVerifiedAmount: 874000,
    submissionDate: '2026-06-28',
    submittedBy: 'Patil Infrastructure & Works Pvt Ltd',
    verificationStatus: 'RETURNED_FOR_CORRECTION',
    verifiedBy: 'Er. Vikram Shinde',
    verificationDate: '2026-07-02',
    engineerRemarks: 'Discrepancy detected! Claimed quantity of 18.5 tonnes is double the weight observed on ground. Only 9.2 tonnes erected; balance claimed as site inventory without delivery slips.',
  },
  {
    id: 'emb-003',
    projectId: 'proj-p105',
    projectCode: 'P105',
    projectName: 'Construction of Concrete Approach Road',
    embNumber: 'EMB-PWD-2025-067',
    pageNumber: 28,
    itemDescription: 'Ready Mixed Concrete M25 for road surface paving laid in uniform panels with dummy joints',
    claimedQuantity: 420,
    measuredQuantity: 420,
    unit: 'Cu.Mtr',
    ratePerUnit: 2650,
    totalClaimedAmount: 1113000,
    totalVerifiedAmount: 1113000,
    submissionDate: '2026-08-01',
    submittedBy: 'Patil Infrastructure & Works Pvt Ltd',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Er. Vikram Shinde',
    verificationDate: '2026-08-06',
    engineerRemarks: 'Batching plant automatic computerized slips reconciled with actual cubic volume.',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-101-1',
    invoiceNumber: 'INV/PATIL/2025/081',
    projectId: 'proj-p101',
    projectCode: 'P101',
    projectName: 'Upgradation of Primary Health Center',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amountClaimed: 700000,
    amountApproved: 700000,
    billDate: '2025-08-15',
    embReference: 'EMB-PWD-2025-044',
    status: 'PAID',
    paymentReference: 'PAY-PFMS-2025-001',
    submittedAt: '2025-08-16T10:00:00Z',
    verifiedAt: '2025-08-20T14:30:00Z',
    verifiedBy: 'Er. Vikram Shinde',
  },
  {
    id: 'inv-102-1',
    invoiceNumber: 'INV/PATIL/2024/112',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amountClaimed: 1150000,
    amountApproved: 1150000,
    billDate: '2024-12-10',
    embReference: 'EMB-PWD-2024-080',
    status: 'PAID',
    paymentReference: 'PAY-PFMS-2024-890',
    submittedAt: '2024-12-11T11:00:00Z',
    verifiedAt: '2024-12-15T16:00:00Z',
    verifiedBy: 'Er. Vikram Shinde',
  },
  {
    id: 'inv-102-2',
    invoiceNumber: 'INV/PATIL/2025/099',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amountClaimed: 1150000,
    amountApproved: 1150000,
    billDate: '2025-04-10',
    embReference: 'EMB-PWD-2024-118',
    status: 'PAID',
    paymentReference: 'PAY-PFMS-2025-412',
    submittedAt: '2025-04-12T09:30:00Z',
    verifiedAt: '2025-04-18T10:00:00Z',
    verifiedBy: 'Er. Vikram Shinde',
  },
  {
    id: 'inv-102-3',
    invoiceNumber: 'INV/PATIL/2026/015',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amountClaimed: 180000,
    billDate: '2026-07-05',
    embReference: 'EMB-PWD-2024-118-REV',
    status: 'PAYMENT_HELD',
    returnedReason: 'Payment held under District Magistrate Order DM/HOLD/2026/03 pending physical verification of steel truss measurement and duplicate project review.',
    submittedAt: '2026-07-06T15:00:00Z',
  },
  {
    id: 'inv-105-1',
    invoiceNumber: 'INV/PATIL/2025/144',
    projectId: 'proj-p105',
    projectCode: 'P105',
    projectName: 'Construction of Concrete Approach Road',
    contractorId: 'usr-contractor-01',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amountClaimed: 1116000,
    amountApproved: 1116000,
    billDate: '2025-09-02',
    embReference: 'EMB-PWD-2025-067',
    status: 'PAID',
    paymentReference: 'PAY-PFMS-2025-788',
    submittedAt: '2025-09-03T11:00:00Z',
    verifiedAt: '2025-09-08T12:00:00Z',
    verifiedBy: 'Er. Vikram Shinde',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    paymentRefNumber: 'PFMS/2025/MH/PUN/00918',
    projectId: 'proj-p101',
    projectCode: 'P101',
    projectName: 'Upgradation of Primary Health Center',
    invoiceId: 'inv-101-1',
    invoiceNumber: 'INV/PATIL/2025/081',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amount: 700000,
    paymentDate: '2025-08-25',
    paymentMode: 'PFMS',
    status: 'PROCESSED',
    bankTransactionId: 'RBI-UTR-20250825991823',
    disbursingOfficer: 'District Planning Officer, Pune',
    remarks: 'First running account (RA) bill cleared after EE technical certification.',
  },
  {
    id: 'pay-002',
    paymentRefNumber: 'PFMS/2024/MH/NSK/04412',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    invoiceId: 'inv-102-1',
    invoiceNumber: 'INV/PATIL/2024/112',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amount: 1150000,
    paymentDate: '2024-12-22',
    paymentMode: 'PFMS',
    status: 'PROCESSED',
    bankTransactionId: 'RBI-UTR-20241222110294',
    disbursingOfficer: 'District Planning Officer, Nashik',
    remarks: 'RA-1 for plinth and RCC column stage.',
  },
  {
    id: 'pay-003',
    paymentRefNumber: 'PFMS/2025/MH/NSK/01198',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    invoiceId: 'inv-102-2',
    invoiceNumber: 'INV/PATIL/2025/099',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amount: 1150000,
    paymentDate: '2025-04-26',
    paymentMode: 'PFMS',
    status: 'PROCESSED',
    bankTransactionId: 'RBI-UTR-20250426883410',
    disbursingOfficer: 'District Planning Officer, Nashik',
    remarks: 'RA-2 for roof structural steel (Currently subject to audit inquiry due to mismatch with ground reality).',
  },
  {
    id: 'pay-004',
    paymentRefNumber: 'PFMS/2025/MH/SAT/00812',
    projectId: 'proj-p105',
    projectCode: 'P105',
    projectName: 'Construction of Concrete Approach Road',
    invoiceId: 'inv-105-1',
    invoiceNumber: 'INV/PATIL/2025/144',
    contractorName: 'Patil Infrastructure & Works Pvt Ltd',
    amount: 1116000,
    paymentDate: '2025-09-15',
    paymentMode: 'PFMS',
    status: 'PROCESSED',
    bankTransactionId: 'RBI-UTR-20250915338102',
    disbursingOfficer: 'District Planning Officer, Satara',
  },
];

export const INITIAL_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'insp-001',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    inspectorName: 'Er. Vikram Shinde',
    inspectorRole: 'Executive Engineer (PWD)',
    inspectionDate: '2026-07-15',
    physicalProgressObserved: 45,
    qualityRating: 'NEEDS_IMPROVEMENT',
    observations:
      'Site visited with Sectional Engineer. Plinth and columns completed. Roof steel structure is incomplete: only 4 bays erected out of 9 bays. Material claimed in RA-2 is not found stored on site. Work has been inactive for the past 6 weeks.',
    correctiveActionsRequired:
      'Contractor must show physical delivery challans for 9.3 tonnes of steel or issue immediate refund of excess RA payment. Work pace must be tripled.',
    geoTag: { lat: 20.0768, lng: 74.1084, accuracyMeters: 4.2 },
    photoUrls: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&auto=format&fit=crop&q=60',
    ],
  },
  {
    id: 'insp-002',
    projectId: 'proj-p101',
    projectCode: 'P101',
    projectName: 'Upgradation of Primary Health Center',
    inspectorName: 'Er. Vikram Shinde',
    inspectorRole: 'Executive Engineer (PWD)',
    inspectionDate: '2026-08-20',
    physicalProgressObserved: 40,
    qualityRating: 'SATISFACTORY',
    observations:
      'Civil remodeling of wards progressing satisfactorily. Vitrified tiles laid with level joints. Wiring conduits installed.',
    geoTag: { lat: 18.1517, lng: 74.5772, accuracyMeters: 3.1 },
    photoUrls: [
      'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=60',
    ],
  },
  {
    id: 'insp-003',
    projectId: 'proj-p105',
    projectCode: 'P105',
    projectName: 'Construction of Concrete Approach Road',
    inspectorName: 'Er. Vikram Shinde',
    inspectorRole: 'Executive Engineer (PWD)',
    inspectionDate: '2026-08-11',
    physicalProgressObserved: 55,
    qualityRating: 'SATISFACTORY',
    observations:
      '1.1 km of 1.8 km CC road completed. Expansion joints sealed with bitumen mastic. Pending cube strength test.',
    geoTag: { lat: 17.6805, lng: 74.0183, accuracyMeters: 5.0 },
    photoUrls: [
      'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&auto=format&fit=crop&q=60',
    ],
  },
];

export const INITIAL_MATERIAL_CERTIFICATES: MaterialCertificate[] = [
  {
    id: 'cert-001',
    projectId: 'proj-p101',
    contractorId: 'usr-contractor-01',
    materialType: 'Grade 53 Ultratech OPC Cement',
    testLabName: 'Government College of Engineering Civil Testing Lab, Pune',
    sampleBatchNo: 'UT-PUN-2025-B4',
    testDate: '2025-04-12',
    testResult: 'COMPLIANT',
    documentUrl: '#cert-doc-01',
    status: 'APPROVED',
    remarks: 'Compressive strength 54.8 N/mm² at 28 days meets IS:12269 specifications.',
    submittedAt: '2025-04-15T11:00:00Z',
  },
  {
    id: 'cert-002',
    projectId: 'proj-p102',
    contractorId: 'usr-contractor-01',
    materialType: 'Fe500D TMT Reinforcement Steel',
    testLabName: 'Regional Material Testing Laboratory, Nashik',
    sampleBatchNo: 'TMT-NSK-2024-912',
    testDate: '2024-09-18',
    testResult: 'COMPLIANT',
    documentUrl: '#cert-doc-02',
    status: 'APPROVED',
    remarks: 'Yield stress 522 MPa, elongation 16.5% compliant with IS:1786.',
    submittedAt: '2024-09-20T14:00:00Z',
  },
  {
    id: 'cert-003',
    projectId: 'proj-p105',
    contractorId: 'usr-contractor-01',
    materialType: 'M25 PQC Concrete Cubes (28-day)',
    testLabName: 'District Quality Control Laboratory, Satara',
    sampleBatchNo: 'CUBE-SAT-2025-88',
    testDate: '2026-08-04',
    testResult: 'PENDING_REVIEW',
    documentUrl: '#cert-doc-03',
    status: 'PENDING',
    remarks: 'Sample collected from Ch. 0+800 to 1+100.',
    submittedAt: '2026-08-05T09:00:00Z',
  },
];

export const INITIAL_SITE_EVIDENCE: SiteEvidence[] = [
  {
    id: 'evid-001',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    uploadedBy: 'Patil Infrastructure & Works Pvt Ltd',
    uploadDate: '2026-07-14',
    title: 'Roof Truss Joint Welding & Column Anchors',
    description: 'Geo-tagged photograph of steel truss erection on columns 1 through 4.',
    stage: 'SUPERSTRUCTURE',
    geoCoordinates: { lat: 20.0768, lng: 74.1084 },
    photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?w=800&auto=format&fit=crop&q=60',
    verifiedByEngineer: true,
    engineerRemarks: 'Verified on site. Notice incomplete trusses beyond axis 4.',
  },
  {
    id: 'evid-002',
    projectId: 'proj-p101',
    projectCode: 'P101',
    projectName: 'Upgradation of Primary Health Center',
    uploadedBy: 'Patil Infrastructure & Works Pvt Ltd',
    uploadDate: '2026-08-18',
    title: 'Emergency Triage Room Tiling and Washroom Fixtures',
    description: 'Geo-tagged photograph of anti-microbial wall tiles and anti-skid floor tiles.',
    stage: 'FINISHING',
    geoCoordinates: { lat: 18.1517, lng: 74.5772 },
    photoUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=60',
    verifiedByEngineer: true,
    engineerRemarks: 'Good quality workmanship verified.',
  },
  {
    id: 'evid-003',
    projectId: 'proj-p105',
    projectCode: 'P105',
    projectName: 'Construction of Concrete Approach Road',
    uploadedBy: 'Patil Infrastructure & Works Pvt Ltd',
    uploadDate: '2026-08-09',
    title: 'Paving of Concrete Approach Road Stretch at Ch 0+950',
    description: 'Geo-tagged evidence during concrete vibro-screeding and curing cover installation.',
    stage: 'SUPERSTRUCTURE',
    geoCoordinates: { lat: 17.6805, lng: 74.0183 },
    photoUrl: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&auto=format&fit=crop&q=60',
    verifiedByEngineer: true,
    engineerRemarks: 'Curing ponding verified.',
  },
];

export const INITIAL_AI_ALERTS: AIAlert[] = [
  {
    id: 'alt-102-crit',
    alertCode: 'ALT/2026/NSK/001',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    district: 'Nashik',
    alertType: 'PHYSICAL_FINANCIAL_MISMATCH',
    riskScore: 86,
    riskLevel: 'CRITICAL',
    dateDetected: '2026-07-16',
    title: 'Disproportionate Fund Expenditure vs Physical Completion',
    description:
      'AI analysis indicates that ₹23.00 Lakh (92% of total sanction) has been disbursed while verified physical site completion is only 45%. Furthermore, project completion is overdue by 285 days.',
    contributingFactors: [
      {
        factor: 'Payment-Progress Mismatch',
        points: 25,
        details: 'Financial progress (92%) exceeds physical progress (45%) by +47 percentage points.',
      },
      {
        factor: 'Delay Probability & Severity',
        points: 18,
        details: '285 days delay past contract date with negative acceleration velocity.',
      },
      {
        factor: 'Cost Deviation',
        points: 15,
        details: 'Full structural steel allocation claimed when only 49% observed on ground.',
      },
      {
        factor: 'Contractor Historical Indicator',
        points: 10,
        details: 'Contractor has 2 other delayed projects in district and returned E-MB bills.',
      },
      {
        factor: 'Duplicate Work Probability',
        points: 18,
        details: '91% semantic and geospatial overlap with newly proposed project P108 in Ward 4.',
      },
    ],
    supportingEvidence: [
      'PFMS Disbursement Vouchers #PFMS/2024/MH/NSK/04412 & #01198',
      'Returned E-MB Record #EMB-PWD-2024-118 Page 52',
      'PWD Executive Engineer Site Inspection Report dated 15-July-2026',
      'Sentence Transformer cosine similarity score of 0.91 with project P108',
    ],
    recommendedAction:
      'Verify physical site measurements via joint inspection, place administrative hold on remaining ₹2.00 Lakh fund balance, and require contractor to submit revised measurement reconciliation before any further claims.',
    disproveCriteria: [
      'Verified site inspection report confirming actual progress >85%',
      'Approved revised E-MB book verified by Executive Engineer explaining measurement delta',
      'Physical receipt of steel inventory verified on-site',
    ],
    status: 'UNDER_REVIEW',
    reviewedBy: 'Arunabh Sengupta (CAG Principal Auditor)',
    reviewedAt: '2026-08-01T11:00:00Z',
    reviewRemarks: 'Opened formal audit case #CAG-2026-MH-042. Requisitioned Treasury bank records.',
    humanDecision: 'VERIFIED_ANOMALY',
  },
  {
    id: 'alt-108-dup',
    alertCode: 'ALT/2026/NSK/002',
    projectId: 'proj-p108',
    projectCode: 'P108',
    projectName: 'Construction of Multipurpose Hall, Ward 4',
    district: 'Nashik',
    alertType: 'DUPLICATE_WORK',
    riskScore: 82,
    riskLevel: 'CRITICAL',
    dateDetected: '2026-07-25',
    title: 'Potential Duplicate / Overlapping Work Detected with P102',
    description:
      'Sentence Transformers semantic similarity score is 91% between Project P108 and Project P102. Both projects are located within 650 meters in Niphad, awarded to the same contractor, and share identical scope items.',
    contributingFactors: [
      {
        factor: 'Semantic Scope Overlap',
        points: 30,
        details: 'Cosine similarity 0.91 on project description, bills of quantities, and architectural type.',
      },
      {
        factor: 'Geospatial Proximity',
        points: 25,
        details: 'Coordinates are within 650 meters in the same gram panchayat jurisdiction.',
      },
      {
        factor: 'Entity Correlation',
        points: 15,
        details: 'Identical contractor (Patil Infrastructure) and same approving subdivision.',
      },
      {
        factor: 'Timeline Anomaly',
        points: 12,
        details: 'Sanctioned shortly before P102 was due for audit review.',
      },
    ],
    supportingEvidence: [
      'Project Charters for P102 and P108',
      'GIS Coordinate distance calculation: 642 meters',
      'Contractor vendor registration code match: VEND-PATIL-8812',
    ],
    recommendedAction:
      'Require District Planning Committee to clarify if P108 is a separate building or an inadvertent duplication of P102 scope. Recommend placing administrative hold on P108 fund releases pending survey verification.',
    disproveCriteria: [
      'Gram Sabha resolution with separate surveyed land ownership (7/12 extract) proving two distinct structures',
      'District Collector site visit verification certificate',
    ],
    status: 'NEW',
  },
  {
    id: 'alt-104-cost',
    alertCode: 'ALT/2026/MUM/001',
    projectId: 'proj-p104',
    projectCode: 'P104',
    projectName: 'Public Library & Digital Learning Center',
    district: 'Mumbai Suburban',
    alertType: 'COST_ANOMALY',
    riskScore: 74,
    riskLevel: 'HIGH',
    dateDetected: '2026-06-30',
    title: 'Unit Cost Deviation & Schedule of Rates Disparity',
    description:
      'Statistical Isolation Forest anomaly model flagged IT equipment unit rates at 32% above standard government procurement benchmarks. Physical completion is lagging at 50% despite 78% expenditure.',
    contributingFactors: [
      {
        factor: 'Cost Deviation from Benchmark',
        points: 28,
        details: 'Work estimate rates for workstation terminals exceed GeM/DSR schedules by 32%.',
      },
      {
        factor: 'Physical/Financial Deviation',
        points: 24,
        details: 'Financial spend (78%) is +28% higher than physical milestone completion (50%).',
      },
      {
        factor: 'Timeline Slippage',
        points: 22,
        details: 'Delayed by 164 days without formal time extension.',
      },
    ],
    supportingEvidence: [
      'Comparison with Maharashtra DSR 2024-25 IT Infrastructure rates',
      'Executive Engineer interim inspection report',
    ],
    recommendedAction:
      'Audit contractor bills against Government e-Marketplace (GeM) prices and inspect on-site delivery of IT hardware.',
    disproveCriteria: [
      'Manufacturer serial numbered delivery challans matching billed specifications',
      'Superintending Engineer rate revision approval order',
    ],
    status: 'UNDER_REVIEW',
  },
  {
    id: 'alt-106-pay',
    alertCode: 'ALT/2026/AUR/001',
    projectId: 'proj-p106',
    projectCode: 'P106',
    projectName: 'Renovation of Water Filtration Plant',
    district: 'Chhatrapati Sambhajinagar',
    alertType: 'PAYMENT_ANOMALY',
    riskScore: 79,
    riskLevel: 'HIGH',
    dateDetected: '2026-05-20',
    title: 'Vendor Mismatch and Unmatched Invoice References',
    description:
      'Payment voucher #PFMS/2025/AUR/08812 cites invoice reference #INV-JAL-091 which has a different PAN from the primary vendor registration.',
    contributingFactors: [
      {
        factor: 'Vendor Identity Mismatch',
        points: 30,
        details: 'Sub-contractor invoice submitted without authorized assignment clause.',
      },
      {
        factor: 'Progress Lag',
        points: 25,
        details: '346 days delay; physical progress is only 30% against 65% funds drawn.',
      },
      {
        factor: 'Inspection Exception',
        points: 24,
        details: 'Quality engineer inspection noted sub-standard filtration media depth.',
      },
    ],
    supportingEvidence: [
      'Treasury payment voucher',
      'PAN card record discrepancy log',
      'District Water Quality Officer inspection notice',
    ],
    recommendedAction:
      'Conduct immediate field verification of water filtration plant equipment and verify sub-contractor authorization.',
    disproveCriteria: [
      'Approved joint venture agreement on government record',
      'Tested water flow rate certificate from approved public health lab',
    ],
    status: 'ESCALATED',
  },
];

export const INITIAL_AUDIT_CASES: AuditCase[] = [
  {
    id: 'case-001',
    caseNumber: 'CAG/MH/2026/CASE-042',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    district: 'Nashik',
    assignedAuditor: 'Arunabh Sengupta (Principal Auditor)',
    riskScore: 86,
    riskLevel: 'CRITICAL',
    status: 'IN_PROGRESS',
    primaryIssue: 'Severe Physical vs Financial Deviation (45% physical vs 92% spent) and Potential Duplicate Work with P108',
    detectedIrregularities: [
      'Over-payment of ₹11.50 Lakh for structural steel without commensurate physical erection',
      'Measurement book EMB-PWD-2024-118 recorded 18.5 tonnes while site inspection verified only 9.2 tonnes',
      'Project P108 sanctioned for ₹24.00 Lakh within 650m for identical scope with same contractor',
      '285 days delay beyond stipulated date with no LD (Liquidated Damages) assessed',
    ],
    auditObservations:
      'Preliminary examination of PFMS records and PWD division accounts reveals that RA-2 bill was passed without mandatory third-party quality lab certificates. A joint verification by Sectional Engineer and District Planning Cell was not conducted prior to voucher settlement.',
    recommendedVerification: [
      'Summon Executive Engineer division measurement books and original steel weighing slips',
      'Reconcile Treasury bank account debits with contractor GST returns',
      'Conduct drone/GIS boundary survey of both P102 and P108 sites',
      'Obtain sworn statement regarding on-site material inventory',
    ],
    disproveConditions: [
      'What would disprove this alert? If the contractor presents verified off-site fabrication storage inspection report countersigned by an independent technical authority, and land records show separate distinct public beneficiary plots.',
    ],
    evidencePackReady: true,
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-08-15T16:30:00Z',
  },
  {
    id: 'case-002',
    caseNumber: 'CAG/MH/2026/CASE-058',
    projectId: 'proj-p104',
    projectCode: 'P104',
    projectName: 'Public Library & Digital Learning Center',
    district: 'Mumbai Suburban',
    assignedAuditor: 'Arunabh Sengupta (Principal Auditor)',
    riskScore: 74,
    riskLevel: 'HIGH',
    status: 'OPEN',
    primaryIssue: 'Cost Escalation and High Rates Deviation from Schedule of Rates',
    detectedIrregularities: [
      'Rates for interior cabling and computer nodes approved at 32% above Mumbai PWD DSR',
      '78% funds released while physical building is only 50% complete',
      'Vendor delivery challans lack official serial numbers',
    ],
    auditObservations:
      'Case opened following AI statistical cost anomaly trigger. Requisition sent to Mumbai Collectorate for complete procurement file.',
    recommendedVerification: [
      'Compare bid evaluation matrix with market rates on GeM',
      'Conduct physical hardware verification at Chembur site',
    ],
    disproveConditions: [
      'Official technical sanction rate justification submitted by Superintending Engineer prior to tender publication.',
    ],
    evidencePackReady: false,
    createdAt: '2026-07-10T14:00:00Z',
    updatedAt: '2026-08-05T09:00:00Z',
  },
];

export const INITIAL_INQUIRY_DIRECTIVES: InquiryDirective[] = [
  {
    id: 'inq-001',
    directiveNumber: 'DM/NSK/INQ/2026/014',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    issuedByCollector: 'Smt. Sunita Rao, IAS (District Collector)',
    assignedAuthority: 'Sub-Divisional Magistrate (SDM), Niphad & Superintending Engineer (PWD)',
    issueDate: '2026-07-22',
    deadlineDate: '2026-08-15',
    reason:
      'Discrepancy of ₹11.50 Lakh in RA-2 steel measurement reported by AI Risk Engine and confirmed by PWD EE preliminary inspection.',
    requiredDeliverables: [
      'Physical site inventory statement of structural steel',
      'Verification of GPS coordinates and ward boundary against Project P108',
      'Explanation from Executive Engineer regarding approval of bill without complete erection',
    ],
    status: 'IN_PROGRESS',
    collectorRemarks:
      'Strict instructions: Complete joint site inspection within 10 days. Ensure no further disbursements until inquiry report is submitted.',
  },
];

export const INITIAL_FUND_HOLDS: FundHold[] = [
  {
    id: 'hold-001',
    projectId: 'proj-p102',
    projectCode: 'P102',
    projectName: 'Rural Community Hall & Multipurpose Shed',
    holdAmount: 200000,
    orderedBy: 'Smt. Sunita Rao, IAS (District Magistrate)',
    reason: 'Precautionary fund freeze on final balance pending completion of inquiry directive DM/NSK/INQ/2026/014.',
    dateImposed: '2026-07-23',
    status: 'ACTIVE_HOLD',
    reviewDeadline: '2026-09-30',
  },
  {
    id: 'hold-002',
    projectId: 'proj-p108',
    projectCode: 'P108',
    projectName: 'Construction of Multipurpose Hall, Ward 4',
    holdAmount: 1800000,
    orderedBy: 'Smt. Sunita Rao, IAS (District Magistrate)',
    reason: 'Temporary administrative hold recommended due to 91% duplicate work anomaly with P102.',
    dateImposed: '2026-07-28',
    status: 'RECOMMENDED_HOLD',
    reviewDeadline: '2026-09-15',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-09-11T19:20:10Z',
    userId: 'usr-admin-01',
    userName: 'Dr. K. Radhakrishnan',
    userRole: UserRole.ADMIN,
    action: 'USER_LOGIN',
    category: 'AUTH',
    details: 'Authenticated via secure SSO credentials.',
    ipAddress: '10.14.22.8',
  },
  {
    id: 'log-002',
    timestamp: '2026-09-11T18:45:22Z',
    userId: 'usr-engineer-01',
    userName: 'Er. Vikram Shinde',
    userRole: UserRole.PWD_ENGINEER,
    action: 'INSPECTION_SUBMITTED',
    category: 'INSPECTION',
    details: 'Recorded physical inspection notes for Project P102.',
    ipAddress: '10.14.22.45',
  },
  {
    id: 'log-003',
    timestamp: '2026-09-11T17:15:40Z',
    userId: 'usr-collector-01',
    userName: 'Smt. Sunita Rao, IAS',
    userRole: UserRole.COLLECTOR,
    action: 'FUND_HOLD_ORDERED',
    category: 'PROJECT',
    details: 'Imposed authorized precautionary fund hold on Project P102 balance (₹2.00 Lakh).',
    ipAddress: '10.14.22.19',
  },
  {
    id: 'log-004',
    timestamp: '2026-09-11T16:30:15Z',
    userId: 'usr-contractor-01',
    userName: 'Rajesh Patil',
    userRole: UserRole.CONTRACTOR,
    action: 'EVIDENCE_UPLOADED',
    category: 'BILL',
    details: 'Uploaded geo-tagged photo evidence for Project P105 approach road paving.',
    ipAddress: '115.112.44.89',
  },
  {
    id: 'log-005',
    timestamp: '2026-09-11T15:10:00Z',
    userId: 'usr-auditor-01',
    userName: 'Arunabh Sengupta',
    userRole: UserRole.CAG_AUDITOR,
    action: 'CASE_UPDATED',
    category: 'AUDIT',
    details: 'Generated consolidated evidence pack dossier for Audit Case #CAG-2026-MH-042.',
    ipAddress: '10.22.50.11',
  },
];

export const INITIAL_SYSTEM_CONFIG: SystemConfig = {
  riskThresholdLowMax: 30,
  riskThresholdMedMax: 60,
  riskThresholdHighMax: 80,
  weights: {
    paymentProgressMismatch: 25,
    delayProbability: 20,
    costDeviation: 20,
    duplicateWorkProbability: 15,
    contractorHistory: 10,
    geographicAnomaly: 10,
  },
  enableEmailAlerts: true,
  enableSmsOtp: true,
  requireDualOtpForRegistration: true,
};

export interface OtpRecord {
  email?: string;
  mobile?: string;
  otp: string;
  expiresAt: number;
  verified: boolean;
  type: 'REGISTRATION' | 'LOGIN' | 'FORGOT_PASSWORD';
}

// In-memory runtime database singleton
class Database {
  users: User[] = [...INITIAL_USERS];
  projects: Project[] = [...INITIAL_PROJECTS];
  workOrders: WorkOrder[] = [...INITIAL_WORK_ORDERS];
  measurements: MeasurementRecord[] = [...INITIAL_MEASUREMENTS];
  invoices: Invoice[] = [...INITIAL_INVOICES];
  payments: Payment[] = [...INITIAL_PAYMENTS];
  inspections: InspectionRecord[] = [...INITIAL_INSPECTIONS];
  materialCertificates: MaterialCertificate[] = [...INITIAL_MATERIAL_CERTIFICATES];
  siteEvidence: SiteEvidence[] = [...INITIAL_SITE_EVIDENCE];
  aiAlerts: AIAlert[] = [...INITIAL_AI_ALERTS];
  auditCases: AuditCase[] = [...INITIAL_AUDIT_CASES];
  inquiryDirectives: InquiryDirective[] = [...INITIAL_INQUIRY_DIRECTIVES];
  fundHolds: FundHold[] = [...INITIAL_FUND_HOLDS];
  auditLogs: AuditLog[] = [...INITIAL_AUDIT_LOGS];
  config: SystemConfig = { ...INITIAL_SYSTEM_CONFIG };
  otps: Map<string, OtpRecord> = new Map();

  addAuditLog(userId: string, userName: string, userRole: UserRole, action: string, category: AuditLog['category'], details: string) {
    const log: AuditLog = {
      id: `log-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      timestamp: new Date().toISOString(),
      userId,
      userName,
      userRole,
      action,
      category,
      details,
      ipAddress: '127.0.0.1',
    };
    this.auditLogs.unshift(log);
    return log;
  }
}

export const db = new Database();
